#!/usr/bin/env bash
# Regenerate THIRD-PARTY.md from the lockfile.
#
# `cargo deny check licenses` is the gate that refuses a licence this
# project may not ship; this file is the list a reader can check it
# against. Generated, so it cannot quietly go stale: CI runs
# `--check` and fails when the committed file and the lockfile disagree.
#
# Usage: scripts/third-party.sh [--check]
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OUT=THIRD-PARTY.md
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cargo metadata --format-version 1 --all-features --locked \
    | python3 -c '
import json, sys

meta = json.load(sys.stdin)
ours = {m["name"] for m in meta["workspace_members"] and []}
workspace = {p["id"] for p in meta["packages"]
             if p["id"] in meta["workspace_members"]}

rows = []
for p in sorted(meta["packages"], key=lambda p: (p["name"].lower(), p["version"])):
    if p["id"] in workspace:
        continue
    licence = p.get("license") or ("see " + (p.get("license_file") or "the crate"))
    rows.append((p["name"], p["version"], licence, p.get("repository") or ""))

print("# Third-party licences")
print()
print("Every crate this workspace builds against, with the licence its")
print("own manifest declares. Generated by `scripts/third-party.sh` from")
print("`Cargo.lock`; `cargo deny check licenses` is what refuses a licence")
print("this project may not ship, and `deny.toml` lists the ones it may.")
print()
print(f"{len(rows)} dependencies.")
print()
print("| Crate | Version | Licence |")
print("|-------|---------|---------|")
for name, version, licence, repo in rows:
    cell = f"[{name}]({repo})" if repo.startswith("http") else name
    print(f"| {cell} | {version} | {licence} |")
' > "$TMP"

if [[ "${1:-}" == "--check" ]]; then
    if ! diff -u "$OUT" "$TMP"; then
        echo "THIRD-PARTY.md is stale: run scripts/third-party.sh" >&2
        exit 1
    fi
    echo "THIRD-PARTY.md matches the lockfile"
    exit 0
fi

mv "$TMP" "$OUT"
trap - EXIT
echo "wrote $OUT"
